dividas/dividas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('dividas_site.urls', namespace='site')),
    path('api/', include('dividasapi.urls', namespace='api')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, path('^__debug__/', include(debug_toolbar.urls)))
    #urlpatterns.append(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

dividas/dividas_site/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
import dividas_site.views as site_views

app_name = 'dividas_site'

urlpatterns = [
    path('', site_views.index, name='index'),
    path('search/', site_views.search, name='search'),
    path('admin/', site_views.admin_index, name='admin'),
    path('admin/dividas/<int:id>', site_views.admin_divida_edit, name='admin_divida_edit'),
    path('admin/dividas/<int:id>/deletar', site_views.admin_divida_deletar, name='admin_divida_deletar'),
    path('admin/dividas/add', site_views.admin_divida_add, name='admin_divida_add'),
    path('admin/entrar', auth_views.login, {'template_name': 'site/login.html'}, name='login'),
    path('admin/sair', auth_views.logout, name='logout')
]

dividas/dividasapi/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
import dividasapi.views as api_views
from dividasapi.api import DividaViewSet

app_name = 'api'

router = DefaultRouter()

router.register(r'dividas', DividaViewSet, 'dividas')

urlpatterns = [
    path('', include(router.urls)),
    path('dividas/', api_views.dividas),
    path('empresas/<int:id>/dividas/', api_views.empresa_dividas)
]

dividas/dividas_site/models.py
from django.db import models

# Create your models here.

dividas/dividasapi/models.py
import os
from binascii import hexlify
from decimal import Decimal
from django.db import models
from django.core.validators import MinValueValidator


class Empresa(models.Model):

    nome = models.CharField('Nome', max_length=100)

    def __str__(self):
        return self.nome


class Devedor(models.Model):

    cpf = models.CharField('cpf', max_length=11)

    def __str__(self):
        return self.cpf

    class Meta:
        indexes = [
            models.Index(fields=['cpf'])
        ]


class Divida(models.Model):

    valor = models.DecimalField('Valor', max_digits=12, decimal_places=2,
                                validators=[MinValueValidator(Decimal('1.0'))]
                                )

    sobre = models.TextField('Sobre a dívida', max_length=300, null=True)
    incluida_em = models.DateTimeField('Incluída em', auto_now_add=True)
    atualizada_em = models.DateTimeField('Atualizada em', auto_now=True)

    cobradora = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    devedor = models.ForeignKey(Devedor, on_delete=models.CASCADE)


class APIKey(models.Model):

    api_key = models.CharField(max_length=37)

    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)

    @classmethod
    def gerar(cls):
        return hexlify(os.urandom(36)).decode()

dividas/dividasapi/forms.py
from django import forms
from dividasapi.models import Divida, Empresa, Devedor
from django.core.exceptions import ObjectDoesNotExist

class ConsultaCPF(forms.Form):

    cpf = forms.CharField(label='CPF', min_length=11, max_length=11,
                          widget=forms.TextInput(attrs={'class': 'input cpf', 'placeholder':'Digite o seu CPF'}))


class DividaForm(forms.ModelForm):

    cpf = forms.CharField(label='CPF', min_length=11, max_length=11,
                          widget=forms.TextInput(attrs={'class': 'input cpf'}))

    cobradora = forms.ModelChoiceField(queryset=Empresa.objects.all())

    def __init__(self, *args, **kwargs):
        super(DividaForm, self).__init__(*args, **kwargs)

        self.fields['valor'].widget.attrs.update({'class': 'input'})
        self.fields['sobre'].widget.attrs.update({'class': 'textarea'})
        self.fields['cobradora'].widget.attrs.update({'class': 'select'})

        try:
            self.fields['cpf'].widget.attrs.update({'value': self.instance.devedor.cpf})
        except ObjectDoesNotExist:
            pass

    class Meta:
        model = Divida
        fields = ['valor', 'sobre']


    def save(self, commit=True):
        cpf = self.cleaned_data['cpf']
        devedor = Devedor.objects.filter(cpf=cpf).first()

        if not devedor:
            devedor = Devedor(cpf=cpf)
            devedor.save()

        self.instance.devedor = devedor
        self.instance.cobradora = self.cleaned_data['cobradora']

        return super(DividaForm, self).save()

dividas/dividas_site/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from dividasapi.models import Divida
from dividasapi.forms import ConsultaCPF, DividaForm


@require_GET
def index(request):
    context = {}

    context['form'] = ConsultaCPF()

    return render(request, 'site/index.html', context)


@require_GET
def search(request):
    context = {}
    form = ConsultaCPF(request.GET or None)

    if form.is_valid():
        cpf = form.cleaned_data['cpf']

        dividas = Divida.objects.filter(devedor__cpf=cpf)
        context['dividas'] = dividas
        context['cpf'] = cpf

        return render(request, 'site/dividas.html', context)

    return redirect('site:index')

@login_required
def admin_index(request):
    context = {}

    dividas = Divida.objects.all()
    context['dividas'] = dividas

    return render(request, 'site/admin.html', context)

@login_required
def admin_divida_add(request):
    context = {}
    form = DividaForm(request.POST or None)

    if form.is_valid():
        divida = form.save()
        messages.success(request, 'Dívida adicionada com sucesso')

        return redirect('site:admin')

    context['form'] = form

    return render(request, 'site/admin_divida_add.html', context)

@login_required
def admin_divida_edit(request, id):
    context = {}

    divida = get_object_or_404(Divida, pk=id)

    form = DividaForm(request.POST or None, instance=divida, initial={'cobradora': divida.cobradora.pk})

    if form.is_valid():
        divida = form.save()
        messages.success(request, 'Dívida atualizada com sucesso')

    context['form'] = form

    return render(request, 'site/admin_divida_edit.html', context)

@login_required
def admin_divida_deletar(request, id):
    divida = get_object_or_404(Divida, pk=id)

    divida.delete()

    messages.success(request, 'Dívida deletada com sucesso')

    return redirect('site:admin')

dividas/dividasapi/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_GET
from django.http import JsonResponse
from django.core import serializers
from dividasapi.forms import ConsultaCPF
from dividasapi.models import Devedor, Divida, Empresa
from dividasapi.serializers import DividaSerializer
from dividasapi.decorators import api_key_required
from django.shortcuts import get_object_or_404


@require_GET
def dividas(request):
    cpf = request.GET.get('cpf', None)

    if not cpf:
        resposta = {
            'mensagem': 'Parâmetro cpf não encontrado',
            'descricao': 'É necessário informar o cpf para realizar a busca por dívidas'
        }

        return JsonResponse(resposta, status=400)

    dividas = Divida.objects.filter(devedor__cpf=cpf)
    dividas_json = DividaSerializer(dividas, many=True)

    return JsonResponse(dividas_json.data, safe=False)


@require_GET
@api_key_required
def empresa_dividas(request, id):
    empresa = Empresa.objects.filter(pk=id).first()

    if not empresa:
        return JsonResponse({'mensagem': 'Empresa não encontrada'}, status=404)

    dividas = empresa.divida_set.all()
    dividas_json = DividaSerializer(dividas, many=True)

    return JsonResponse(dividas_json.data, safe=False)

dividas/dividas_site/templates/site/admin.html
{% extends "site/template.html" %}
{% load dividas_tags %}
{% block content %}
{% include "site/nav_admin.html" %}
<section class="section">
  <div class="container">
    <div class="level">
      <div class="level-left">
        <h1 class="title">Dívidas</h1>
      </div>
      <div class="level-right">
        <a href="{% url 'site:admin_divida_add' %}" class="button is-info">Adicionar dívida</a>
      </div>
    </div>
    {% if messages %}
    {% for mensagem in messages %}
    <div class="notification is-{{mensagem.tags}}">
      <button class="delete"></button>
      {{ mensagem }}
    </div>
    {% endfor %}
    {% endif %}

    {% if dividas %}
    <table class="table is-striped is-fullwidth">
      <thead>
        <th>Devedor</th>
        <th>Cobrador</th>
        <th>Valor</th>
        <th>Data Inclusão</th>
        <th>Sobre</th>
        <th>Ações</th>
      </thead>
      <tbody>
        {% for divida in dividas %}
        <tr>
          <td class="cpf">{{divida.devedor.cpf}}</td>
          <td>{{divida.cobradora.nome}}</td>
          <td>{{divida.valor|formatar_moeda}}</td>
          <td>{{divida.incluida_em}}</td>
          <td>{% if divida.sobre %} {{divida.sobre}} {% endif %}</td>
          <td>
            <span class="icon">
              <form>
              <a class="button is-text" href="{% url 'site:admin_divida_edit' divida.id %}"><i class="fas fa-pencil-alt"></i></a>
              </form>
            </span>
            <span class="icon">
              <form method="post" action="{% url 'site:admin_divida_deletar' divida.id %}">
                {% csrf_token %}
                  <button type="submit" class="button is-text">
                    <span class="icon">
                      <i class="fas fa-trash-alt"></i>
                    </span>
                  </button>
              <input type="hidden" name="id" value="{{divida.id}}"/>
              </form>
            </span>
          </td>

        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>Nenhuma dívida encontrada</p>
    {% endif %}
  </div>
</section>

{% block javascript %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.min.js" integrity="sha256-Cq7XEyDcEipCpZODrMe4Bxukqlx8R9ZndzIYs4wytEM=" crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

  <script>
  $(document).ready(function() {
    $('.cpf').mask('000.000.000.00');
  })
  </script>
  {{ block.super }}

{% endblock %}

{% endblock %}

dividas/dividas_site/templates/site/admin_divida_add.html
{% extends "site/template.html" %}

{% block content %}

{% include "site/nav_admin.html" %}

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-4 is-offset-4">
        <h1 class="title">Nova dívida</h1>
        <form id="cadastrar-divida-form" method="post">
          {{ form.non_field_errors }}
          {% csrf_token %}
          <div class="field">
            {% for field in form %}
            <label class="label">{{field.label}}</label>
            <div class="control">
              {{field}}
            </div>
            <p class="help">{{field.help_text}}</p>
            {% if field.errors %}
            <p class="help is-danger">
              {% for error in field.errors %}
              {{error}}.
              {% endfor %}
            </p>
            {% endif %}
            {% endfor %}
          </div>
          <div class="field">
            <div class="control">
              <button type="submit" class="button is-info">Cadastrar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

{% block javascript %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.min.js" integrity="sha256-Cq7XEyDcEipCpZODrMe4Bxukqlx8R9ZndzIYs4wytEM=" crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

  <script>
  $(document).ready(function() {
    $('.cpf').mask('000.000.000.00');

    $('#cadastrar-divida-form').submit(function () {
      $('input.cpf').val($('input.cpf').cleanVal());
    });
  });
  </script>
  {{ block.super }}

  {% endblock %}

dividas/dividas_site/templates/site/admin_divida_edit.html
{% extends "site/template.html" %}
{% block content %}
{% include "site/nav_admin.html" %}

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-4 is-offset-4">
        <h1 class="title">Editar dívida #{{form.instance.id}}</h1>
        {% if messages %}
        {% for mensagem in messages %}
        <div class="notification is-{{mensagem.tags}}">
          <button class="delete"></button>
          {{ mensagem }}
        {% endfor %}
        </div>
        {% endif %}
        <form method="post">
          {{ form.non_field_errors }}
          {% csrf_token %}
          {% for field in form %}
          <div class="field">
            <label class="label">{{field.label}}</label>
            <div class="control">
              {{field}}
            </div>
            <p class="help">{{field.help_text}}</p>
            {% if field.errors %}
            <p class="help is-danger">
            {% for error in field.errors %}
            {{error}}.
            {% endfor %}
            </p>
              {% endif %}
          </div>
          {% endfor %}
          <div class="field">
            <div class="control">
              <button type="submit" class="button is-primary">Salvar</button>
            </div>
          </div>
        </form>
      </div>
    </div>

  </div>
</section>
{% endblock %}

dividas/dividas_site/templates/site/dividas.html
{% extends "site/template.html" %}
{% load static %}
{% load dividas_tags %}
{% block content %}
<section class="hero is-fullheight is-info">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2 has-text-centered container-dividas-content">
        <div class="content dividas-content">
          {% if dividas %}
          <h1 class="title"> Dívidas associadas ao CPF <span class="cpf">{{ cpf }}</span></h1>
          <div class="" style="padding-left: 10px; padding-rigth: 10px; background-color: white">
            <table class="table is-striped">
              <thead>
                <tr>
                  <th>Valor</th>
                  <th>Cobrador</th>
                  <th>Incluída em</th>
                  <th>Sobre</th>
                </tr>
              </thead>
              <tbody>
                {% for divida in dividas %}
                <tr>
                  <td>
                    {{ divida.valor|formatar_moeda }}
                  </td>
                  <td>
                    {{divida.cobradora.nome}}
                  </td>
                  <td>
                    {{divida.incluida_em}}
                  </td>
                  <td>
                    {% if divida.sobre %}
                    {{divida.sobre}}
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% else %}
          <h1 class="title">Parabéns! O Seu nome está limpo.</h1>
          <figure>
            <img class="image is-128x128" src="{% static 'imgs/maps-and-flags.png' %}">
          </figure>
          <a href="{% url 'dividas_site:index'%}" class="button is-danger">Fazer nova consulta</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>

% block javascript %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.min.js" integrity="sha256-Cq7XEyDcEipCpZODrMe4Bxukqlx8R9ZndzIYs4wytEM=" crossorigin="anonymous"></script>

  <script>
  $(document).ready(function() {
    $('.cpf').mask('000.000.000.00');
  })
  </script>
  {{ block.super }}

{% endblock %}

dividas/dividas_site/templates/site/index.html
{% extends "site/template.html" %}
{% block content %}
  <section class="hero is-info is-fullheight">
    <div class="hero-body">
      <div class="container has-text-centered">
        <p><h1 class="is-size-1">Nome sujo? Verifique agora mesmo!</h1></p>
        <form id="nome-sujo-form" method="get" action="{% url 'site:search' %}">
          {% csrf_token %}
          <div class="field has-addons has-addons-centered">
            <p class="control">
              {{form.cpf }}
            </p>
            <p class="control">
              <button class="button is-primary" type="submit">Verificar</button>
            </p>
          </div>
          {% if form.cpf.errors %}
          <p class="control">
            <p class="help is-danger">
              <strong>
              {% for error in form.cpf.errors %}
              {{ error }}.
              {% endfor %}
              </strong>
            </p>
          </p>
          {% endif %}
        </form>
      </div>
    </div>
  </section>
{% endblock %}
{% block javascript %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.min.js" integrity="sha256-Cq7XEyDcEipCpZODrMe4Bxukqlx8R9ZndzIYs4wytEM=" crossorigin="anonymous"></script>

  <script>
  $(document).ready(function() {
    $('input.cpf').mask('000.000.000.00');

    $('#nome-sujo-form').submit(function() {
      console.log($('input.cpf').cleanVal());
      $('input.cpf').val($('input.cpf').cleanVal());
    });

  })
  </script>
  {{ block.super }}
{% endblock %}

dividas/dividas_site/templates/site/login.html
{% extends "site/template.html" %}
{% block content %}
<section class="hero is-primary is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns">
        <div class="column is-4 is-offset-4">
          <h1 class="title">Entrar</h1>
          <form method="post">
            {% csrf_token %}
            <p class="is-danger">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
            </p>
            <div class="field">
              <div class="control">
                <input class="input" type="text" id="{{form.username.id_for_label}}" name="{{form.username.name}}" required
                  placeholder="Usuário" />
                <p class="help">{{form.username.help_text}}</p>
                {% if form.username.errors %}
                <p class="help is-danger">
                  {% for error in form.username.errors %}
                  {{error}}.
                  {% endfor %}
                </p>
                {% endif %}
              </div>
            </div>

            <div class="field">
              <div class="control">
                <input class="input" type="password" id="{{form.password.id_for_label}}" name="{{form.password.name}}" required
                  placeholder="Senha" />

                <p class="help">{{form.password.help_text}}</p>
                {% if form.password.errors %}
                <p class="help is-danger">
                  {% for error in form.password.errors %}
                  {{error}}.
                  {% endfor %}
                </p>
                {% endif %}

              </div>
            </div>

            <div class="field">
              <div class="control">
                <button type="submit" class="button is-link">Entrar</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

dividas/dividas_site/templates/site/nav_admin.html
<nav class="navbar is-link" role="navigation" aria-label="main navigation">
  <div class="navbar-menu is-active">
    <div class="navbar-end">
      <a class="navbar-item" href="{% url 'site:index' %}" class="">Home</a>
      <a class="navbar-item" href="{% url 'site:logout' %}">Sair</a>
    </div>
  </div>
</nav>

dividas/dividas_site/templates/site/template.html
<!DOCTYPE HTML>
{% load static %}
<html>
<head>
  <title>{{title}}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block css %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css" integrity="sha256-2k1KVsNPRXxZOsXQ8aqcZ9GOOwmJTMoOB5o5Qp1d6/s=" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'css/site.css' %}" />
  {% endblock %}
  {% block javascript %}
  {% endblock %}
</head>

<body>
  {% block content %}
  {% endblock %}
</body>

</html>